# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.LL_spARCH <- function(pars, param) {
    .Call('_spGARCH_LL_spARCH', PACKAGE = 'spGARCH', pars, param)
}

.LL_EspARCH <- function(pars, param) {
    .Call('_spGARCH_LL_EspARCH', PACKAGE = 'spGARCH', pars, param)
}

.LL_spARCHX <- function(pars, param) {
    .Call('_spGARCH_LL_spARCHX', PACKAGE = 'spGARCH', pars, param)
}

.LL_EspARCHX <- function(pars, param) {
    .Call('_spGARCH_LL_EspARCHX', PACKAGE = 'spGARCH', pars, param)
}

.LL_SARspARCH <- function(pars, param) {
    .Call('_spGARCH_LL_SARspARCH', PACKAGE = 'spGARCH', pars, param)
}

.LL_SAREspARCH <- function(pars, param) {
    .Call('_spGARCH_LL_SAREspARCH', PACKAGE = 'spGARCH', pars, param)
}

.LL_SARspARCHX <- function(pars, param) {
    .Call('_spGARCH_LL_SARspARCHX', PACKAGE = 'spGARCH', pars, param)
}

.LL_SAREspARCHX <- function(pars, param) {
    .Call('_spGARCH_LL_SAREspARCHX', PACKAGE = 'spGARCH', pars, param)
}

.Simulation_CPP <- function(eps, Wsparse, alpha) {
    .Call('_spGARCH_Simulation_CPP', PACKAGE = 'spGARCH', eps, Wsparse, alpha)
}

.Simulation_CPP_E <- function(eps, Wsparse, alpha, b) {
    .Call('_spGARCH_Simulation_CPP_E', PACKAGE = 'spGARCH', eps, Wsparse, alpha, b)
}

.asdgCMatrix <- function(IN) {
    .Call('_spGARCH_asdgCMatrix', PACKAGE = 'spGARCH', IN)
}

